export { __resetAuthRedirectForTests, buildApiHeaders } from './_request';
export { analyzeStream } from './search';

export { authApi } from './auth';
export { searchApi, competitorApi, viabilityApi, companyAnalysisApi, intelligenceApi, cnaeApi, rfSearchApi, smartRelationsApi, integrationsApi, autoProspApi } from './search';
export { plansApi, billingApi, affiliateApi } from './billing';
export { leadsApi, pipelineApi, tagsApi, notificationsApi, pushApi } from './crm';
export { userApi, workspaceProfileApi, onboardingApi, activityApi } from './user';

export type {
    SessionUser,
    UserProfileUpdate,
    UserProfileResponse,
    Place,
    PlaceDetail,
    Analysis,
    Lead,
    SearchHistoryItem,
    CompetitorRankEntry,
    CompetitorAnalysisResult,
    ScoredPlace,
    AiPlaybook,
    AiMarketInsights,
    MarketReport,
    SegmentBreakdown,
    ViabilityReport,
    ViabilityMode,
    ViabilityAnalyzeParams,
    CompanyAnalysisReport,
    CompanyAnalysisParams,
    IntelligenceReportItem,
    PlanFromApi,
    StarterPromoInfo,
    PromoValidateResponse,
    CheckoutResponse,
    AnalyzeProgressStep,
    AnalyzeStreamCallbacks,
    AnalyzeStreamOptions,
    NotificationType,
    NotificationItem,
    LeadTagItem,
    LeadAnalysisListItem,
    LeadStats,
    PipelineRecommendation,
    PipelineStats,
    PipelineBrief,
    ConversionStats,
    WorkspaceProfile,
    WorkspaceProfileCnpjLookup,
    CnaeCode,
    RfCompanyResult,
    RelatedCompany,
    SmartRelationsResult,
    AutoProspStats,
    AutoProspLead,
    AutoProspRun,
    AutoProspProfile,
    AutoProspConfig,
    PaginatedResponse,
    AffiliateMe,
    AffiliateStats,
} from './types';
