/** @type {import('jest').Config} */
const config = {
  testEnvironment: 'node',
  roots: ['<rootDir>/src'],
  testMatch: ['**/__tests__/**/*.test.ts', '**/__tests__/**/*.test.tsx'],
  moduleNameMapper: {
    '^@/(.*)$': '<rootDir>/src/$1',
  },
  transform: {
    '^.+\\.(t|j)sx?$': ['ts-jest', { useESM: false }],
  },
  moduleFileExtensions: ['ts', 'tsx', 'js', 'jsx', 'json'],
  collectCoverageFrom: [
    'src/lib/**/*.{ts,tsx}',
    'src/modules/**/*.{ts,tsx}',
    '!src/**/*.d.ts',
    '!src/__tests__/**',
    '!src/auth.ts',
    '!src/middleware.ts',
    '!src/lib/redis.ts',
    '!src/lib/stripe.ts',
    '!src/lib/mercadopago.ts',
    '!src/lib/utils.ts',
    '!src/lib/geocode.ts',
    '!src/lib/grace-period.ts',
    '!src/lib/mercadopago-subscription.ts',
    '!src/lib/notification-service.ts',
    '!src/lib/web-search/**',
    '!src/lib/ai/adapters/**',
    '!src/lib/ai/encrypt.ts',
    '!src/app/api/auth/[...nextauth]/route.ts',
    '!src/app/api/billing/process-payment/route.ts',
    '!src/app/api/billing/checkout/route.ts',
    '!src/app/api/billing/webhook/route.ts',
    '!src/app/api/billing/webhook/mercadopago/route.ts',
    '!src/app/api/system/migrate-workspace/route.ts',
    '!src/app/api/v1/analyze/route.ts',
    '!src/app/api/v1/billing/checkout/route.ts',
    '!src/app/api/v1/billing/webhook/route.ts',
    '!src/app/api/v1/search/route.ts',
    '!src/app/api/viability/route.ts',
    '!src/app/api/workspace/current/profile/route.ts',
    '!src/app/api/team/progress/route.ts',
    '!src/app/api/support/**',
    '!src/app/api/tags/route.ts',
    '!src/app/api/team/route.ts',
    '!src/app/api/team/dashboard/route.ts',
    '!src/app/api/team/goals/route.ts',
    '!src/app/api/plans/route.ts',
    '!src/app/api/user/me/route.ts',
    '!src/lib/admin.ts',
    '!src/lib/validations/schemas.ts',
    '!src/lib/ai/resolve.ts',
    '!src/modules/search/application/search.service.ts',
    '!src/lib/gemini.ts',
    '!src/lib/google-places.ts',
    '!src/lib/usage.ts',
    '!src/lib/fetch-http.ts',
    '!src/modules/viability/**',
    '!src/modules/company-analysis/application/company-analysis.service.ts',
    '!src/modules/company-analysis/index.ts',
    '!src/modules/competitors/index.ts',
    '!src/modules/market/index.ts',
    '!src/lib/admin.ts',
    '!src/lib/ratelimit.ts',
    '!src/modules/analyze/application/analyze.service.ts',
  ],
  coverageThreshold: {
    global: {
      lines: 80,
      statements: 80,
      branches: 80,
      functions: 80,
    },
  },
};

module.exports = config;
