FROM node:20-alpine

WORKDIR /app
COPY package*.json ./
RUN npm ci

COPY . .
EXPOSE 3000

# build em runtime dev? depende do projeto. Aqui vou deixar dev-friendly:
CMD ["npm", "run", "dev", "--", "--hostname", "0.0.0.0", "--port", "3000"]
