/**
 * Tipos do Google Places API (Table A) — categorias e subcategorias para filtro de busca.
 * Usado em includedType na Text Search.
 * @see https://developers.google.com/maps/documentation/places/web-service/place-types
 */

export interface PlaceTypeOption {
  value: string;
  label: string;
}

export interface PlaceTypeCategory {
  label: string;
  types: PlaceTypeOption[];
}

/** Categorias e tipos (Table A) — completos conforme documentação Google Places. */
export const PLACE_TYPE_CATEGORIES: PlaceTypeCategory[] = [
  {
    label: 'Negócios',
    types: [
      { value: 'business_center', label: 'Centro de negócios' },
      { value: 'corporate_office', label: 'Escritório corporativo' },
      { value: 'coworking_space', label: 'Coworking' },
      { value: 'farm', label: 'Fazenda' },
      { value: 'manufacturer', label: 'Fabricante' },
      { value: 'ranch', label: 'Rancho' },
      { value: 'supplier', label: 'Fornecedor' },
      { value: 'television_studio', label: 'Estúdio de TV' },
    ],
  },
  {
    label: 'Serviços',
    types: [
      { value: 'lawyer', label: 'Advogado' },
      { value: 'accounting', label: 'Contabilidade' },
      { value: 'insurance_agency', label: 'Seguradora' },
      { value: 'real_estate_agency', label: 'Imobiliária' },
      { value: 'travel_agency', label: 'Agência de viagens' },
      { value: 'marketing_consultant', label: 'Consultoria de marketing' },
      { value: 'barber_shop', label: 'Barbearia' },
      { value: 'beauty_salon', label: 'Salão de beleza' },
      { value: 'hair_care', label: 'Cabelo' },
      { value: 'hair_salon', label: 'Salão de cabelo' },
      { value: 'plumber', label: 'Encanador' },
      { value: 'electrician', label: 'Eletricista' },
      { value: 'moving_company', label: 'Mudanças' },
      { value: 'locksmith', label: 'Chaveiro' },
      { value: 'painter', label: 'Pintor' },
      { value: 'roofing_contractor', label: 'Telhados' },
      { value: 'tailor', label: 'Alfaiate' },
      { value: 'florist', label: 'Florista' },
      { value: 'courier_service', label: 'Entregas' },
      { value: 'consultant', label: 'Consultor' },
      { value: 'child_care_agency', label: 'Creche' },
      { value: 'employment_agency', label: 'Agência de emprego' },
      { value: 'catering_service', label: 'Buffet' },
      { value: 'funeral_home', label: 'Funerária' },
      { value: 'laundry', label: 'Lavanderia' },
      { value: 'pet_care', label: 'Pet shop / Veterinário' },
      { value: 'veterinary_care', label: 'Veterinário' },
      { value: 'storage', label: 'Self storage' },
      { value: 'tour_agency', label: 'Agência de turismo' },
      { value: 'tourist_information_center', label: 'Centro de informações turísticas' },
    ],
  },
  {
    label: 'Finanças',
    types: [
      { value: 'accounting', label: 'Contabilidade' },
      { value: 'atm', label: 'Caixa eletrônico' },
      { value: 'bank', label: 'Banco' },
    ],
  },
  {
    label: 'Alimentação e bebidas',
    types: [
      { value: 'restaurant', label: 'Restaurante' },
      { value: 'cafe', label: 'Café' },
      { value: 'coffee_shop', label: 'Cafeteria' },
      { value: 'bakery', label: 'Padaria' },
      { value: 'bar', label: 'Bar' },
      { value: 'fast_food_restaurant', label: 'Fast food' },
      { value: 'food_court', label: 'Food court' },
      { value: 'meal_delivery', label: 'Delivery' },
      { value: 'meal_takeaway', label: 'Para viagem' },
      { value: 'supermarket', label: 'Supermercado' },
      { value: 'grocery_store', label: 'Mercado' },
      { value: 'convenience_store', label: 'Loja de conveniência' },
      { value: 'ice_cream_shop', label: 'Sorveteria' },
      { value: 'brazilian_restaurant', label: 'Restaurante brasileiro' },
      { value: 'italian_restaurant', label: 'Restaurante italiano' },
      { value: 'japanese_restaurant', label: 'Restaurante japonês' },
      { value: 'mexican_restaurant', label: 'Restaurante mexicano' },
      { value: 'pizza_restaurant', label: 'Pizzaria' },
      { value: 'sandwich_shop', label: 'Lanches' },
      { value: 'seafood_restaurant', label: 'Frutos do mar' },
      { value: 'steak_house', label: 'Churrascaria' },
      { value: 'brewery', label: 'Cervejaria' },
      { value: 'pub', label: 'Pub' },
      { value: 'wine_bar', label: 'Wine bar' },
    ],
  },
  {
    label: 'Comércio e varejo',
    types: [
      { value: 'store', label: 'Loja' },
      { value: 'clothing_store', label: 'Loja de roupas' },
      { value: 'electronics_store', label: 'Loja de eletrônicos' },
      { value: 'furniture_store', label: 'Móveis' },
      { value: 'hardware_store', label: 'Material de construção' },
      { value: 'shopping_mall', label: 'Shopping' },
      { value: 'department_store', label: 'Loja de departamentos' },
      { value: 'book_store', label: 'Livraria' },
      { value: 'gift_shop', label: 'Loja de presentes' },
      { value: 'jewelry_store', label: 'Joalheria' },
      { value: 'shoe_store', label: 'Calçados' },
      { value: 'sporting_goods_store', label: 'Artigos esportivos' },
      { value: 'bicycle_store', label: 'Bicicletas' },
      { value: 'pet_store', label: 'Pet shop' },
      { value: 'liquor_store', label: 'Bebidas' },
      { value: 'discount_store', label: 'Atacado/Desconto' },
      { value: 'wholesaler', label: 'Atacadista' },
      { value: 'convenience_store', label: 'Loja de conveniência' },
      { value: 'market', label: 'Mercado' },
      { value: 'food_store', label: 'Loja de alimentos' },
      { value: 'cosmetics_store', label: 'Cosméticos' },
      { value: 'cell_phone_store', label: 'Celulares' },
      { value: 'auto_parts_store', label: 'Peças automotivas' },
    ],
  },
  {
    label: 'Automotivo',
    types: [
      { value: 'car_dealer', label: 'Concessionária' },
      { value: 'car_rental', label: 'Aluguel de carros' },
      { value: 'car_repair', label: 'Oficina mecânica' },
      { value: 'car_wash', label: 'Lava-rápido' },
      { value: 'gas_station', label: 'Posto de gasolina' },
      { value: 'electric_vehicle_charging_station', label: 'Posto de recarga elétrica' },
      { value: 'parking', label: 'Estacionamento' },
      { value: 'parking_garage', label: 'Garagem' },
      { value: 'parking_lot', label: 'Estacionamento' },
      { value: 'tire_shop', label: 'Pneus' },
      { value: 'truck_dealer', label: 'Caminhões' },
    ],
  },
  {
    label: 'Saúde e bem-estar',
    types: [
      { value: 'hospital', label: 'Hospital' },
      { value: 'pharmacy', label: 'Farmácia' },
      { value: 'drugstore', label: 'Drogaria' },
      { value: 'doctor', label: 'Médico' },
      { value: 'dental_clinic', label: 'Clínica odontológica' },
      { value: 'dentist', label: 'Dentista' },
      { value: 'medical_clinic', label: 'Clínica médica' },
      { value: 'spa', label: 'Spa' },
      { value: 'gym', label: 'Academia' },
      { value: 'fitness_center', label: 'Centro fitness' },
      { value: 'chiropractor', label: 'Quiropraxia' },
      { value: 'physiotherapist', label: 'Fisioterapia' },
      { value: 'massage', label: 'Massagem' },
      { value: 'massage_spa', label: 'Spa de massagem' },
      { value: 'yoga_studio', label: 'Yoga' },
      { value: 'wellness_center', label: 'Centro de bem-estar' },
      { value: 'medical_lab', label: 'Laboratório' },
      { value: 'skin_care_clinic', label: 'Clínica de pele' },
      { value: 'sauna', label: 'Sauna' },
    ],
  },
  {
    label: 'Educação',
    types: [
      { value: 'school', label: 'Escola' },
      { value: 'university', label: 'Universidade' },
      { value: 'library', label: 'Biblioteca' },
      { value: 'preschool', label: 'Pré-escola' },
      { value: 'primary_school', label: 'Ensino fundamental' },
      { value: 'secondary_school', label: 'Ensino médio' },
      { value: 'educational_institution', label: 'Instituição de ensino' },
      { value: 'research_institute', label: 'Instituto de pesquisa' },
    ],
  },
  {
    label: 'Hospedagem',
    types: [
      { value: 'hotel', label: 'Hotel' },
      { value: 'lodging', label: 'Hospedagem' },
      { value: 'hostel', label: 'Hostel' },
      { value: 'guest_house', label: 'Casa de hóspedes' },
      { value: 'bed_and_breakfast', label: 'Bed & breakfast' },
      { value: 'motel', label: 'Motel' },
      { value: 'resort_hotel', label: 'Resort' },
      { value: 'campground', label: 'Camping' },
      { value: 'inn', label: 'Pousada' },
    ],
  },
  {
    label: 'Entretenimento e lazer',
    types: [
      { value: 'movie_theater', label: 'Cinema' },
      { value: 'bowling_alley', label: 'Boliche' },
      { value: 'amusement_park', label: 'Parque de diversões' },
      { value: 'aquarium', label: 'Aquário' },
      { value: 'zoo', label: 'Zoológico' },
      { value: 'casino', label: 'Cassino' },
      { value: 'night_club', label: 'Boate' },
      { value: 'concert_hall', label: 'Casa de shows' },
      { value: 'stadium', label: 'Estádio' },
      { value: 'arena', label: 'Arena' },
      { value: 'park', label: 'Parque' },
      { value: 'museum', label: 'Museu' },
      { value: 'art_gallery', label: 'Galeria de arte' },
      { value: 'tourist_attraction', label: 'Ponto turístico' },
      { value: 'water_park', label: 'Parque aquático' },
      { value: 'garden', label: 'Jardim' },
      { value: 'botanical_garden', label: 'Jardim botânico' },
      { value: 'convention_center', label: 'Centro de convenções' },
      { value: 'event_venue', label: 'Espaço para eventos' },
      { value: 'banquet_hall', label: 'Salão de festas' },
      { value: 'wedding_venue', label: 'Espaço para casamentos' },
    ],
  },
  {
    label: 'Esportes',
    types: [
      { value: 'gym', label: 'Academia' },
      { value: 'fitness_center', label: 'Centro fitness' },
      { value: 'golf_course', label: 'Golfe' },
      { value: 'stadium', label: 'Estádio' },
      { value: 'swimming_pool', label: 'Piscina' },
      { value: 'sports_complex', label: 'Complexo esportivo' },
      { value: 'sports_club', label: 'Clube esportivo' },
      { value: 'tennis_court', label: 'Quadra de tênis' },
      { value: 'ice_skating_rink', label: 'Ringue de gelo' },
      { value: 'ski_resort', label: 'Estação de esqui' },
      { value: 'playground', label: 'Playground' },
      { value: 'athletic_field', label: 'Campo esportivo' },
    ],
  },
  {
    label: 'Transporte',
    types: [
      { value: 'airport', label: 'Aeroporto' },
      { value: 'international_airport', label: 'Aeroporto internacional' },
      { value: 'bus_station', label: 'Rodoviária' },
      { value: 'bus_stop', label: 'Parada de ônibus' },
      { value: 'train_station', label: 'Estação de trem' },
      { value: 'subway_station', label: 'Metrô' },
      { value: 'transit_station', label: 'Estação de transporte' },
      { value: 'gas_station', label: 'Posto de gasolina' },
      { value: 'parking', label: 'Estacionamento' },
      { value: 'taxi_stand', label: 'Ponto de táxi' },
      { value: 'ferry_terminal', label: 'Balsa' },
      { value: 'car_rental', label: 'Aluguel de carros' },
    ],
  },
  {
    label: 'Governo',
    types: [
      { value: 'city_hall', label: 'Prefeitura' },
      { value: 'courthouse', label: 'Fórum/Tribunal' },
      { value: 'embassy', label: 'Embaixada' },
      { value: 'fire_station', label: 'Bombeiros' },
      { value: 'government_office', label: 'Repartição pública' },
      { value: 'police', label: 'Polícia' },
      { value: 'post_office', label: 'Correios' },
    ],
  },
  {
    label: 'Cultura e arte',
    types: [
      { value: 'museum', label: 'Museu' },
      { value: 'art_gallery', label: 'Galeria de arte' },
      { value: 'art_museum', label: 'Museu de arte' },
      { value: 'history_museum', label: 'Museu de história' },
      { value: 'performing_arts_theater', label: 'Teatro' },
      { value: 'auditorium', label: 'Auditório' },
      { value: 'monument', label: 'Monumento' },
      { value: 'historical_place', label: 'Lugar histórico' },
      { value: 'cultural_landmark', label: 'Marco cultural' },
      { value: 'cultural_center', label: 'Centro cultural' },
      { value: 'opera_house', label: 'Ópera' },
      { value: 'concert_hall', label: 'Sala de concertos' },
    ],
  },
  {
    label: 'Religião',
    types: [
      { value: 'church', label: 'Igreja' },
      { value: 'synagogue', label: 'Sinagoga' },
      { value: 'mosque', label: 'Mesquita' },
      { value: 'hindu_temple', label: 'Templo hindu' },
      { value: 'buddhist_temple', label: 'Templo budista' },
    ],
  },
  {
    label: 'Instalações e outros',
    types: [
      { value: 'public_bathroom', label: 'Banheiro público' },
      { value: 'stable', label: 'Estábulo' },
    ],
  },
  {
    label: 'Moradia',
    types: [
      { value: 'apartment_building', label: 'Edifício residencial' },
      { value: 'apartment_complex', label: 'Condomínio' },
      { value: 'condominium_complex', label: 'Condomínio' },
      { value: 'housing_complex', label: 'Conjunto habitacional' },
    ],
  },
  {
    label: 'Natureza',
    types: [
      { value: 'beach', label: 'Praia' },
      { value: 'park', label: 'Parque' },
      { value: 'national_park', label: 'Parque nacional' },
      { value: 'nature_preserve', label: 'Reserva natural' },
      { value: 'lake', label: 'Lago' },
      { value: 'river', label: 'Rio' },
      { value: 'mountain_peak', label: 'Pico' },
      { value: 'scenic_spot', label: 'Mirante' },
      { value: 'garden', label: 'Jardim' },
      { value: 'botanical_garden', label: 'Jardim botânico' },
    ],
  },
];

export function getPlaceTypeByValue(value: string): PlaceTypeOption | undefined {
  for (const cat of PLACE_TYPE_CATEGORIES) {
    const found = cat.types.find((t) => t.value === value);
    if (found) return found;
  }
  return undefined;
}
